filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/log/containers/*-${data.container.id}.log

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '172.18.0.10:9200'
  #username: 'elastic'
  #password: 'tphOuNomrXQUXbb9C=XS'
